# Generated by Django 5.1.6 on 2025-02-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemestabelecimento',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='imagemestabelecimento',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='negocios.cidade'),
        ),
    ]
