# Generated by Django 5.1.6 on 2025-02-22 22:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_imagemestabelecimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
