# Generated by Django 5.1.6 on 2025-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_rename_redes_sociais_estabelecimento_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
