# Generated by Django 5.1.6 on 2025-03-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_cidade_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
